-- Drop table

-- DROP TABLE dbqrsys.dbo.FACTURA

CREATE TABLE dbqrsys.dbo.FACTURA (
	IDFACTURA int NOT NULL IDENTITY(1,1),
	NOFACTURA varchar(50) NOT NULL,
	FECHA datetime(3) NOT NULL,
	IDUSUARIO int NOT NULL,
	PROVEEDOR varchar(250),
	TIPO varchar(50),
	SUBTIPO varchar(50),
	ESQUEMA varchar(250),
	TIPOCAMBIO float,
	MONEDA varchar(50),
	ALMACEN varchar(150),
	OBSERVACION varchar(1000),
	IDPROVEEDOR varchar(10),
	IDALMACEN int,
	CVEOBS int,
	CVEDOC varchar(20),
	CONSTRAINT FACTURA_PK PRIMARY KEY (IDFACTURA)
) go;


-- Drop table

-- DROP TABLE dbqrsys.dbo.PERFIL

CREATE TABLE dbqrsys.dbo.PERFIL (
	IDPERFIL int NOT NULL IDENTITY(1,1),
	DESCRIPCION varchar(50),
	CONSTRAINT PERFIL_PK PRIMARY KEY (IDPERFIL)
) go;


-- Drop table

-- DROP TABLE dbqrsys.dbo.SERIE

CREATE TABLE dbqrsys.dbo.SERIE (
	IDSERIE int NOT NULL IDENTITY(1,1),
	SERIE varchar(30) NOT NULL,
	ARTICULO varchar(100) NOT NULL,
	DESCRIPCION varchar(250) NOT NULL,
	IDFACTURA int NOT NULL,
	IDUSUARIO int,
	ADUANA varchar(250),
	PEDIMENTO varchar(50),
	FECHAPEDIMENTO date(0),
	LOTE varchar(30),
	IMPRESO int,
	SELECCIONAR bit DEFAULT ((0)),
	SAE bit,
	CONSTRAINT SERIE_PK PRIMARY KEY (IDSERIE),
	CONSTRAINT SERIE_FACTURA_FK FOREIGN KEY (IDFACTURA) REFERENCES dbqrsys.dbo.FACTURA(IDFACTURA) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT SERIE_USUARIO_FK FOREIGN KEY (IDUSUARIO) REFERENCES dbqrsys.dbo.USUARIO(IDUSUARIO) ON DELETE RESTRICT ON UPDATE RESTRICT
) go;


-- Drop table

-- DROP TABLE dbqrsys.dbo.USUARIO

CREATE TABLE dbqrsys.dbo.USUARIO (
	IDUSUARIO int NOT NULL IDENTITY(1,1),
	NOMBRE varchar(50) NOT NULL,
	PASSWORD varchar(500) NOT NULL,
	CORREO varchar(50) NOT NULL,
	FECHA datetime(3) NOT NULL,
	ESTADO bit DEFAULT ((1)) NOT NULL,
	ALMACEN varchar(100) NOT NULL,
	IDPERFIL int NOT NULL,
	CONSTRAINT USUARIO_PK PRIMARY KEY (IDUSUARIO),
	CONSTRAINT USUARIO_PERFIL_FK FOREIGN KEY (IDPERFIL) REFERENCES dbqrsys.dbo.PERFIL(IDPERFIL) ON DELETE RESTRICT ON UPDATE RESTRICT
) go;
