package com.etiquetas.qrsys.s.model;
// Generated Jul 27, 2018 2:46:39 PM by Hibernate Tools 4.3.1



/**
 * CompcClib01 generated by hbm2java
 */
public class CompcClib01  implements java.io.Serializable {


     private String claveDoc;

    public CompcClib01() {
    }

    public CompcClib01(String claveDoc) {
       this.claveDoc = claveDoc;
    }
   
    public String getClaveDoc() {
        return this.claveDoc;
    }
    
    public void setClaveDoc(String claveDoc) {
        this.claveDoc = claveDoc;
    }




}


