package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * EnlaceLtpd01 generated by hbm2java
 */
public class EnlaceLtpd01  implements java.io.Serializable {


     private EnlaceLtpd01Id id;

    public EnlaceLtpd01() {
    }

    public EnlaceLtpd01(EnlaceLtpd01Id id) {
       this.id = id;
    }
   
    public EnlaceLtpd01Id getId() {
        return this.id;
    }
    
    public void setId(EnlaceLtpd01Id id) {
        this.id = id;
    }




}


