package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * EnlaceLtpd01Id generated by hbm2java
 */
public class EnlaceLtpd01Id  implements java.io.Serializable {


     private int ELtpd;
     private Integer regLtpd;
     private Double cantidad;
     private Double pxrs;

    public EnlaceLtpd01Id() {
    }

	
    public EnlaceLtpd01Id(int ELtpd) {
        this.ELtpd = ELtpd;
    }
    public EnlaceLtpd01Id(int ELtpd, Integer regLtpd, Double cantidad, Double pxrs) {
       this.ELtpd = ELtpd;
       this.regLtpd = regLtpd;
       this.cantidad = cantidad;
       this.pxrs = pxrs;
    }
   
    public int getELtpd() {
        return this.ELtpd;
    }
    
    public void setELtpd(int ELtpd) {
        this.ELtpd = ELtpd;
    }
    public Integer getRegLtpd() {
        return this.regLtpd;
    }
    
    public void setRegLtpd(Integer regLtpd) {
        this.regLtpd = regLtpd;
    }
    public Double getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Double cantidad) {
        this.cantidad = cantidad;
    }
    public Double getPxrs() {
        return this.pxrs;
    }
    
    public void setPxrs(Double pxrs) {
        this.pxrs = pxrs;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnlaceLtpd01Id) ) return false;
		 EnlaceLtpd01Id castOther = ( EnlaceLtpd01Id ) other; 
         
		 return (this.getELtpd()==castOther.getELtpd())
 && ( (this.getRegLtpd()==castOther.getRegLtpd()) || ( this.getRegLtpd()!=null && castOther.getRegLtpd()!=null && this.getRegLtpd().equals(castOther.getRegLtpd()) ) )
 && ( (this.getCantidad()==castOther.getCantidad()) || ( this.getCantidad()!=null && castOther.getCantidad()!=null && this.getCantidad().equals(castOther.getCantidad()) ) )
 && ( (this.getPxrs()==castOther.getPxrs()) || ( this.getPxrs()!=null && castOther.getPxrs()!=null && this.getPxrs().equals(castOther.getPxrs()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getELtpd();
         result = 37 * result + ( getRegLtpd() == null ? 0 : this.getRegLtpd().hashCode() );
         result = 37 * result + ( getCantidad() == null ? 0 : this.getCantidad().hashCode() );
         result = 37 * result + ( getPxrs() == null ? 0 : this.getPxrs().hashCode() );
         return result;
   }   


}


