package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Hnumser01Id generated by hbm2java
 */
public class Hnumser01Id  implements java.io.Serializable {


     private String cveArt;
     private String numSer;
     private Integer tipMov;
     private String tipDoc;
     private String cveDoc;
     private int almacen;
     private Integer regSerie;
     private Date fecha;
     private String status;
     private Integer noPar;

    public Hnumser01Id() {
    }

	
    public Hnumser01Id(String cveArt, String numSer, int almacen) {
        this.cveArt = cveArt;
        this.numSer = numSer;
        this.almacen = almacen;
    }
    public Hnumser01Id(String cveArt, String numSer, Integer tipMov, String tipDoc, String cveDoc, int almacen, Integer regSerie, Date fecha, String status, Integer noPar) {
       this.cveArt = cveArt;
       this.numSer = numSer;
       this.tipMov = tipMov;
       this.tipDoc = tipDoc;
       this.cveDoc = cveDoc;
       this.almacen = almacen;
       this.regSerie = regSerie;
       this.fecha = fecha;
       this.status = status;
       this.noPar = noPar;
    }
   
    public String getCveArt() {
        return this.cveArt;
    }
    
    public void setCveArt(String cveArt) {
        this.cveArt = cveArt;
    }
    public String getNumSer() {
        return this.numSer;
    }
    
    public void setNumSer(String numSer) {
        this.numSer = numSer;
    }
    public Integer getTipMov() {
        return this.tipMov;
    }
    
    public void setTipMov(Integer tipMov) {
        this.tipMov = tipMov;
    }
    public String getTipDoc() {
        return this.tipDoc;
    }
    
    public void setTipDoc(String tipDoc) {
        this.tipDoc = tipDoc;
    }
    public String getCveDoc() {
        return this.cveDoc;
    }
    
    public void setCveDoc(String cveDoc) {
        this.cveDoc = cveDoc;
    }
    public int getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(int almacen) {
        this.almacen = almacen;
    }
    public Integer getRegSerie() {
        return this.regSerie;
    }
    
    public void setRegSerie(Integer regSerie) {
        this.regSerie = regSerie;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getNoPar() {
        return this.noPar;
    }
    
    public void setNoPar(Integer noPar) {
        this.noPar = noPar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Hnumser01Id) ) return false;
		 Hnumser01Id castOther = ( Hnumser01Id ) other; 
         
		 return ( (this.getCveArt()==castOther.getCveArt()) || ( this.getCveArt()!=null && castOther.getCveArt()!=null && this.getCveArt().equals(castOther.getCveArt()) ) )
 && ( (this.getNumSer()==castOther.getNumSer()) || ( this.getNumSer()!=null && castOther.getNumSer()!=null && this.getNumSer().equals(castOther.getNumSer()) ) )
 && ( (this.getTipMov()==castOther.getTipMov()) || ( this.getTipMov()!=null && castOther.getTipMov()!=null && this.getTipMov().equals(castOther.getTipMov()) ) )
 && ( (this.getTipDoc()==castOther.getTipDoc()) || ( this.getTipDoc()!=null && castOther.getTipDoc()!=null && this.getTipDoc().equals(castOther.getTipDoc()) ) )
 && ( (this.getCveDoc()==castOther.getCveDoc()) || ( this.getCveDoc()!=null && castOther.getCveDoc()!=null && this.getCveDoc().equals(castOther.getCveDoc()) ) )
 && (this.getAlmacen()==castOther.getAlmacen())
 && ( (this.getRegSerie()==castOther.getRegSerie()) || ( this.getRegSerie()!=null && castOther.getRegSerie()!=null && this.getRegSerie().equals(castOther.getRegSerie()) ) )
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) )
 && ( (this.getStatus()==castOther.getStatus()) || ( this.getStatus()!=null && castOther.getStatus()!=null && this.getStatus().equals(castOther.getStatus()) ) )
 && ( (this.getNoPar()==castOther.getNoPar()) || ( this.getNoPar()!=null && castOther.getNoPar()!=null && this.getNoPar().equals(castOther.getNoPar()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCveArt() == null ? 0 : this.getCveArt().hashCode() );
         result = 37 * result + ( getNumSer() == null ? 0 : this.getNumSer().hashCode() );
         result = 37 * result + ( getTipMov() == null ? 0 : this.getTipMov().hashCode() );
         result = 37 * result + ( getTipDoc() == null ? 0 : this.getTipDoc().hashCode() );
         result = 37 * result + ( getCveDoc() == null ? 0 : this.getCveDoc().hashCode() );
         result = 37 * result + this.getAlmacen();
         result = 37 * result + ( getRegSerie() == null ? 0 : this.getRegSerie().hashCode() );
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         result = 37 * result + ( getStatus() == null ? 0 : this.getStatus().hashCode() );
         result = 37 * result + ( getNoPar() == null ? 0 : this.getNoPar().hashCode() );
         return result;
   }   


}


