package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * Hnumser01 generated by hbm2java
 */
public class Hnumser01  implements java.io.Serializable {


     private Hnumser01Id id;

    public Hnumser01() {
    }

    public Hnumser01(Hnumser01Id id) {
       this.id = id;
    }
   
    public Hnumser01Id getId() {
        return this.id;
    }
    
    public void setId(Hnumser01Id id) {
        this.id = id;
    }




}


