package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * Minve01 generated by hbm2java
 */
public class Minve01  implements java.io.Serializable {


     private Minve01Id id;

    public Minve01() {
    }

    public Minve01(Minve01Id id) {
       this.id = id;
    }
   
    public Minve01Id getId() {
        return this.id;
    }
    
    public void setId(Minve01Id id) {
        this.id = id;
    }




}


