package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Minve01Id generated by hbm2java
 */
public class Minve01Id  implements java.io.Serializable {


     private String cveArt;
     private int almacen;
     private int numMov;
     private int cveCpto;
     private Date fechaDocu;
     private String tipoDoc;
     private String refer;
     private String claveClpv;
     private String vend;
     private Double cant;
     private Double cantCost;
     private Double precio;
     private Double costo;
     private String afecCoi;
     private Integer cveObs;
     private Integer regSerie;
     private String uniVenta;
     private Integer ELtpd;
     private Double existG;
     private Double existencia;
     private String tipoProd;
     private Double factorCon;
     private Date fechaelab;
     private Integer ctlpol;
     private String cveFolio;
     private Integer signo;
     private String costeado;
     private Double costoPromIni;
     private Double costoPromFin;
     private Double costoPromGral;
     private String desdeInve;
     private Integer movEnlazado;

    public Minve01Id() {
    }

	
    public Minve01Id(String cveArt, int almacen, int numMov, int cveCpto) {
        this.cveArt = cveArt;
        this.almacen = almacen;
        this.numMov = numMov;
        this.cveCpto = cveCpto;
    }
    public Minve01Id(String cveArt, int almacen, int numMov, int cveCpto, Date fechaDocu, String tipoDoc, String refer, String claveClpv, String vend, Double cant, Double cantCost, Double precio, Double costo, String afecCoi, Integer cveObs, Integer regSerie, String uniVenta, Integer ELtpd, Double existG, Double existencia, String tipoProd, Double factorCon, Date fechaelab, Integer ctlpol, String cveFolio, Integer signo, String costeado, Double costoPromIni, Double costoPromFin, Double costoPromGral, String desdeInve, Integer movEnlazado) {
       this.cveArt = cveArt;
       this.almacen = almacen;
       this.numMov = numMov;
       this.cveCpto = cveCpto;
       this.fechaDocu = fechaDocu;
       this.tipoDoc = tipoDoc;
       this.refer = refer;
       this.claveClpv = claveClpv;
       this.vend = vend;
       this.cant = cant;
       this.cantCost = cantCost;
       this.precio = precio;
       this.costo = costo;
       this.afecCoi = afecCoi;
       this.cveObs = cveObs;
       this.regSerie = regSerie;
       this.uniVenta = uniVenta;
       this.ELtpd = ELtpd;
       this.existG = existG;
       this.existencia = existencia;
       this.tipoProd = tipoProd;
       this.factorCon = factorCon;
       this.fechaelab = fechaelab;
       this.ctlpol = ctlpol;
       this.cveFolio = cveFolio;
       this.signo = signo;
       this.costeado = costeado;
       this.costoPromIni = costoPromIni;
       this.costoPromFin = costoPromFin;
       this.costoPromGral = costoPromGral;
       this.desdeInve = desdeInve;
       this.movEnlazado = movEnlazado;
    }
   
    public String getCveArt() {
        return this.cveArt;
    }
    
    public void setCveArt(String cveArt) {
        this.cveArt = cveArt;
    }
    public int getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(int almacen) {
        this.almacen = almacen;
    }
    public int getNumMov() {
        return this.numMov;
    }
    
    public void setNumMov(int numMov) {
        this.numMov = numMov;
    }
    public int getCveCpto() {
        return this.cveCpto;
    }
    
    public void setCveCpto(int cveCpto) {
        this.cveCpto = cveCpto;
    }
    public Date getFechaDocu() {
        return this.fechaDocu;
    }
    
    public void setFechaDocu(Date fechaDocu) {
        this.fechaDocu = fechaDocu;
    }
    public String getTipoDoc() {
        return this.tipoDoc;
    }
    
    public void setTipoDoc(String tipoDoc) {
        this.tipoDoc = tipoDoc;
    }
    public String getRefer() {
        return this.refer;
    }
    
    public void setRefer(String refer) {
        this.refer = refer;
    }
    public String getClaveClpv() {
        return this.claveClpv;
    }
    
    public void setClaveClpv(String claveClpv) {
        this.claveClpv = claveClpv;
    }
    public String getVend() {
        return this.vend;
    }
    
    public void setVend(String vend) {
        this.vend = vend;
    }
    public Double getCant() {
        return this.cant;
    }
    
    public void setCant(Double cant) {
        this.cant = cant;
    }
    public Double getCantCost() {
        return this.cantCost;
    }
    
    public void setCantCost(Double cantCost) {
        this.cantCost = cantCost;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public String getAfecCoi() {
        return this.afecCoi;
    }
    
    public void setAfecCoi(String afecCoi) {
        this.afecCoi = afecCoi;
    }
    public Integer getCveObs() {
        return this.cveObs;
    }
    
    public void setCveObs(Integer cveObs) {
        this.cveObs = cveObs;
    }
    public Integer getRegSerie() {
        return this.regSerie;
    }
    
    public void setRegSerie(Integer regSerie) {
        this.regSerie = regSerie;
    }
    public String getUniVenta() {
        return this.uniVenta;
    }
    
    public void setUniVenta(String uniVenta) {
        this.uniVenta = uniVenta;
    }
    public Integer getELtpd() {
        return this.ELtpd;
    }
    
    public void setELtpd(Integer ELtpd) {
        this.ELtpd = ELtpd;
    }
    public Double getExistG() {
        return this.existG;
    }
    
    public void setExistG(Double existG) {
        this.existG = existG;
    }
    public Double getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(Double existencia) {
        this.existencia = existencia;
    }
    public String getTipoProd() {
        return this.tipoProd;
    }
    
    public void setTipoProd(String tipoProd) {
        this.tipoProd = tipoProd;
    }
    public Double getFactorCon() {
        return this.factorCon;
    }
    
    public void setFactorCon(Double factorCon) {
        this.factorCon = factorCon;
    }
    public Date getFechaelab() {
        return this.fechaelab;
    }
    
    public void setFechaelab(Date fechaelab) {
        this.fechaelab = fechaelab;
    }
    public Integer getCtlpol() {
        return this.ctlpol;
    }
    
    public void setCtlpol(Integer ctlpol) {
        this.ctlpol = ctlpol;
    }
    public String getCveFolio() {
        return this.cveFolio;
    }
    
    public void setCveFolio(String cveFolio) {
        this.cveFolio = cveFolio;
    }
    public Integer getSigno() {
        return this.signo;
    }
    
    public void setSigno(Integer signo) {
        this.signo = signo;
    }
    public String getCosteado() {
        return this.costeado;
    }
    
    public void setCosteado(String costeado) {
        this.costeado = costeado;
    }
    public Double getCostoPromIni() {
        return this.costoPromIni;
    }
    
    public void setCostoPromIni(Double costoPromIni) {
        this.costoPromIni = costoPromIni;
    }
    public Double getCostoPromFin() {
        return this.costoPromFin;
    }
    
    public void setCostoPromFin(Double costoPromFin) {
        this.costoPromFin = costoPromFin;
    }
    public Double getCostoPromGral() {
        return this.costoPromGral;
    }
    
    public void setCostoPromGral(Double costoPromGral) {
        this.costoPromGral = costoPromGral;
    }
    public String getDesdeInve() {
        return this.desdeInve;
    }
    
    public void setDesdeInve(String desdeInve) {
        this.desdeInve = desdeInve;
    }
    public Integer getMovEnlazado() {
        return this.movEnlazado;
    }
    
    public void setMovEnlazado(Integer movEnlazado) {
        this.movEnlazado = movEnlazado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Minve01Id) ) return false;
		 Minve01Id castOther = ( Minve01Id ) other; 
         
		 return ( (this.getCveArt()==castOther.getCveArt()) || ( this.getCveArt()!=null && castOther.getCveArt()!=null && this.getCveArt().equals(castOther.getCveArt()) ) )
 && (this.getAlmacen()==castOther.getAlmacen())
 && (this.getNumMov()==castOther.getNumMov())
 && (this.getCveCpto()==castOther.getCveCpto())
 && ( (this.getFechaDocu()==castOther.getFechaDocu()) || ( this.getFechaDocu()!=null && castOther.getFechaDocu()!=null && this.getFechaDocu().equals(castOther.getFechaDocu()) ) )
 && ( (this.getTipoDoc()==castOther.getTipoDoc()) || ( this.getTipoDoc()!=null && castOther.getTipoDoc()!=null && this.getTipoDoc().equals(castOther.getTipoDoc()) ) )
 && ( (this.getRefer()==castOther.getRefer()) || ( this.getRefer()!=null && castOther.getRefer()!=null && this.getRefer().equals(castOther.getRefer()) ) )
 && ( (this.getClaveClpv()==castOther.getClaveClpv()) || ( this.getClaveClpv()!=null && castOther.getClaveClpv()!=null && this.getClaveClpv().equals(castOther.getClaveClpv()) ) )
 && ( (this.getVend()==castOther.getVend()) || ( this.getVend()!=null && castOther.getVend()!=null && this.getVend().equals(castOther.getVend()) ) )
 && ( (this.getCant()==castOther.getCant()) || ( this.getCant()!=null && castOther.getCant()!=null && this.getCant().equals(castOther.getCant()) ) )
 && ( (this.getCantCost()==castOther.getCantCost()) || ( this.getCantCost()!=null && castOther.getCantCost()!=null && this.getCantCost().equals(castOther.getCantCost()) ) )
 && ( (this.getPrecio()==castOther.getPrecio()) || ( this.getPrecio()!=null && castOther.getPrecio()!=null && this.getPrecio().equals(castOther.getPrecio()) ) )
 && ( (this.getCosto()==castOther.getCosto()) || ( this.getCosto()!=null && castOther.getCosto()!=null && this.getCosto().equals(castOther.getCosto()) ) )
 && ( (this.getAfecCoi()==castOther.getAfecCoi()) || ( this.getAfecCoi()!=null && castOther.getAfecCoi()!=null && this.getAfecCoi().equals(castOther.getAfecCoi()) ) )
 && ( (this.getCveObs()==castOther.getCveObs()) || ( this.getCveObs()!=null && castOther.getCveObs()!=null && this.getCveObs().equals(castOther.getCveObs()) ) )
 && ( (this.getRegSerie()==castOther.getRegSerie()) || ( this.getRegSerie()!=null && castOther.getRegSerie()!=null && this.getRegSerie().equals(castOther.getRegSerie()) ) )
 && ( (this.getUniVenta()==castOther.getUniVenta()) || ( this.getUniVenta()!=null && castOther.getUniVenta()!=null && this.getUniVenta().equals(castOther.getUniVenta()) ) )
 && ( (this.getELtpd()==castOther.getELtpd()) || ( this.getELtpd()!=null && castOther.getELtpd()!=null && this.getELtpd().equals(castOther.getELtpd()) ) )
 && ( (this.getExistG()==castOther.getExistG()) || ( this.getExistG()!=null && castOther.getExistG()!=null && this.getExistG().equals(castOther.getExistG()) ) )
 && ( (this.getExistencia()==castOther.getExistencia()) || ( this.getExistencia()!=null && castOther.getExistencia()!=null && this.getExistencia().equals(castOther.getExistencia()) ) )
 && ( (this.getTipoProd()==castOther.getTipoProd()) || ( this.getTipoProd()!=null && castOther.getTipoProd()!=null && this.getTipoProd().equals(castOther.getTipoProd()) ) )
 && ( (this.getFactorCon()==castOther.getFactorCon()) || ( this.getFactorCon()!=null && castOther.getFactorCon()!=null && this.getFactorCon().equals(castOther.getFactorCon()) ) )
 && ( (this.getFechaelab()==castOther.getFechaelab()) || ( this.getFechaelab()!=null && castOther.getFechaelab()!=null && this.getFechaelab().equals(castOther.getFechaelab()) ) )
 && ( (this.getCtlpol()==castOther.getCtlpol()) || ( this.getCtlpol()!=null && castOther.getCtlpol()!=null && this.getCtlpol().equals(castOther.getCtlpol()) ) )
 && ( (this.getCveFolio()==castOther.getCveFolio()) || ( this.getCveFolio()!=null && castOther.getCveFolio()!=null && this.getCveFolio().equals(castOther.getCveFolio()) ) )
 && ( (this.getSigno()==castOther.getSigno()) || ( this.getSigno()!=null && castOther.getSigno()!=null && this.getSigno().equals(castOther.getSigno()) ) )
 && ( (this.getCosteado()==castOther.getCosteado()) || ( this.getCosteado()!=null && castOther.getCosteado()!=null && this.getCosteado().equals(castOther.getCosteado()) ) )
 && ( (this.getCostoPromIni()==castOther.getCostoPromIni()) || ( this.getCostoPromIni()!=null && castOther.getCostoPromIni()!=null && this.getCostoPromIni().equals(castOther.getCostoPromIni()) ) )
 && ( (this.getCostoPromFin()==castOther.getCostoPromFin()) || ( this.getCostoPromFin()!=null && castOther.getCostoPromFin()!=null && this.getCostoPromFin().equals(castOther.getCostoPromFin()) ) )
 && ( (this.getCostoPromGral()==castOther.getCostoPromGral()) || ( this.getCostoPromGral()!=null && castOther.getCostoPromGral()!=null && this.getCostoPromGral().equals(castOther.getCostoPromGral()) ) )
 && ( (this.getDesdeInve()==castOther.getDesdeInve()) || ( this.getDesdeInve()!=null && castOther.getDesdeInve()!=null && this.getDesdeInve().equals(castOther.getDesdeInve()) ) )
 && ( (this.getMovEnlazado()==castOther.getMovEnlazado()) || ( this.getMovEnlazado()!=null && castOther.getMovEnlazado()!=null && this.getMovEnlazado().equals(castOther.getMovEnlazado()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCveArt() == null ? 0 : this.getCveArt().hashCode() );
         result = 37 * result + this.getAlmacen();
         result = 37 * result + this.getNumMov();
         result = 37 * result + this.getCveCpto();
         result = 37 * result + ( getFechaDocu() == null ? 0 : this.getFechaDocu().hashCode() );
         result = 37 * result + ( getTipoDoc() == null ? 0 : this.getTipoDoc().hashCode() );
         result = 37 * result + ( getRefer() == null ? 0 : this.getRefer().hashCode() );
         result = 37 * result + ( getClaveClpv() == null ? 0 : this.getClaveClpv().hashCode() );
         result = 37 * result + ( getVend() == null ? 0 : this.getVend().hashCode() );
         result = 37 * result + ( getCant() == null ? 0 : this.getCant().hashCode() );
         result = 37 * result + ( getCantCost() == null ? 0 : this.getCantCost().hashCode() );
         result = 37 * result + ( getPrecio() == null ? 0 : this.getPrecio().hashCode() );
         result = 37 * result + ( getCosto() == null ? 0 : this.getCosto().hashCode() );
         result = 37 * result + ( getAfecCoi() == null ? 0 : this.getAfecCoi().hashCode() );
         result = 37 * result + ( getCveObs() == null ? 0 : this.getCveObs().hashCode() );
         result = 37 * result + ( getRegSerie() == null ? 0 : this.getRegSerie().hashCode() );
         result = 37 * result + ( getUniVenta() == null ? 0 : this.getUniVenta().hashCode() );
         result = 37 * result + ( getELtpd() == null ? 0 : this.getELtpd().hashCode() );
         result = 37 * result + ( getExistG() == null ? 0 : this.getExistG().hashCode() );
         result = 37 * result + ( getExistencia() == null ? 0 : this.getExistencia().hashCode() );
         result = 37 * result + ( getTipoProd() == null ? 0 : this.getTipoProd().hashCode() );
         result = 37 * result + ( getFactorCon() == null ? 0 : this.getFactorCon().hashCode() );
         result = 37 * result + ( getFechaelab() == null ? 0 : this.getFechaelab().hashCode() );
         result = 37 * result + ( getCtlpol() == null ? 0 : this.getCtlpol().hashCode() );
         result = 37 * result + ( getCveFolio() == null ? 0 : this.getCveFolio().hashCode() );
         result = 37 * result + ( getSigno() == null ? 0 : this.getSigno().hashCode() );
         result = 37 * result + ( getCosteado() == null ? 0 : this.getCosteado().hashCode() );
         result = 37 * result + ( getCostoPromIni() == null ? 0 : this.getCostoPromIni().hashCode() );
         result = 37 * result + ( getCostoPromFin() == null ? 0 : this.getCostoPromFin().hashCode() );
         result = 37 * result + ( getCostoPromGral() == null ? 0 : this.getCostoPromGral().hashCode() );
         result = 37 * result + ( getDesdeInve() == null ? 0 : this.getDesdeInve().hashCode() );
         result = 37 * result + ( getMovEnlazado() == null ? 0 : this.getMovEnlazado().hashCode() );
         return result;
   }   


}


