package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mult01 generated by hbm2java
 */
public class Mult01  implements java.io.Serializable {


     private Mult01Id id;
     private String status;
     private String ctrlAlm;
     private Double exist;
     private Double stockMin;
     private Double stockMax;
     private Double compXRec;
     private String uuid;
     private Date versionSinc;

    public Mult01() {
    }

	
    public Mult01(Mult01Id id) {
        this.id = id;
    }
    public Mult01(Mult01Id id, String status, String ctrlAlm, Double exist, Double stockMin, Double stockMax, Double compXRec, String uuid, Date versionSinc) {
       this.id = id;
       this.status = status;
       this.ctrlAlm = ctrlAlm;
       this.exist = exist;
       this.stockMin = stockMin;
       this.stockMax = stockMax;
       this.compXRec = compXRec;
       this.uuid = uuid;
       this.versionSinc = versionSinc;
    }
   
    public Mult01Id getId() {
        return this.id;
    }
    
    public void setId(Mult01Id id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getCtrlAlm() {
        return this.ctrlAlm;
    }
    
    public void setCtrlAlm(String ctrlAlm) {
        this.ctrlAlm = ctrlAlm;
    }
    public Double getExist() {
        return this.exist;
    }
    
    public void setExist(Double exist) {
        this.exist = exist;
    }
    public Double getStockMin() {
        return this.stockMin;
    }
    
    public void setStockMin(Double stockMin) {
        this.stockMin = stockMin;
    }
    public Double getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(Double stockMax) {
        this.stockMax = stockMax;
    }
    public Double getCompXRec() {
        return this.compXRec;
    }
    
    public void setCompXRec(Double compXRec) {
        this.compXRec = compXRec;
    }
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Date getVersionSinc() {
        return this.versionSinc;
    }
    
    public void setVersionSinc(Date versionSinc) {
        this.versionSinc = versionSinc;
    }




}


