package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * Mult01Id generated by hbm2java
 */
public class Mult01Id  implements java.io.Serializable {


     private String cveArt;
     private int cveAlm;

    public Mult01Id() {
    }

    public Mult01Id(String cveArt, int cveAlm) {
       this.cveArt = cveArt;
       this.cveAlm = cveAlm;
    }
   
    public String getCveArt() {
        return this.cveArt;
    }
    
    public void setCveArt(String cveArt) {
        this.cveArt = cveArt;
    }
    public int getCveAlm() {
        return this.cveAlm;
    }
    
    public void setCveAlm(int cveAlm) {
        this.cveAlm = cveAlm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof Mult01Id) ) return false;
		 Mult01Id castOther = ( Mult01Id ) other; 
         
		 return ( (this.getCveArt()==castOther.getCveArt()) || ( this.getCveArt()!=null && castOther.getCveArt()!=null && this.getCveArt().equals(castOther.getCveArt()) ) )
 && (this.getCveAlm()==castOther.getCveAlm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCveArt() == null ? 0 : this.getCveArt().hashCode() );
         result = 37 * result + this.getCveAlm();
         return result;
   }   


}


