package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * ParCompcClib01 generated by hbm2java
 */
public class ParCompcClib01  implements java.io.Serializable {


     private ParCompcClib01Id id;

    public ParCompcClib01() {
    }

    public ParCompcClib01(ParCompcClib01Id id) {
       this.id = id;
    }
   
    public ParCompcClib01Id getId() {
        return this.id;
    }
    
    public void setId(ParCompcClib01Id id) {
        this.id = id;
    }




}


