package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * ParCompc01 generated by hbm2java
 */
public class ParCompc01  implements java.io.Serializable {


     private ParCompc01Id id;
     private String cveArt;
     private Double cant;
     private Double pxr;
     private Double prec;
     private Double cost;
     private Double impu1;
     private Double impu2;
     private Double impu3;
     private Double impu4;
     private Short imp1apla;
     private Short imp2apla;
     private Short imp3apla;
     private Short imp4apla;
     private Double totimp1;
     private Double totimp2;
     private Double totimp3;
     private Double totimp4;
     private Double descu;
     private String actInv;
     private Double tipCam;
     private String uniVenta;
     private String tipoElem;
     private String tipoProd;
     private Integer cveObs;
     private Integer regSerie;
     private Integer ELtpd;
     private Double factconv;
     private Double costDev;
     private Integer numAlm;
     private Double mindirecto;
     private Integer numMov;
     private Double totPartida;
     private String manIeps;
     private Integer aplManImp;
     private Double cuotaIeps;
     private String aplManIeps;
     private Double mtoPorc;
     private Double mtoCuota;
     private Integer cveEsq;
     private String descrArt;

    public ParCompc01() {
    }

	
    public ParCompc01(ParCompc01Id id) {
        this.id = id;
    }
    public ParCompc01(ParCompc01Id id, String cveArt, Double cant, Double pxr, Double prec, Double cost, Double impu1, Double impu2, Double impu3, Double impu4, Short imp1apla, Short imp2apla, Short imp3apla, Short imp4apla, Double totimp1, Double totimp2, Double totimp3, Double totimp4, Double descu, String actInv, Double tipCam, String uniVenta, String tipoElem, String tipoProd, Integer cveObs, Integer regSerie, Integer ELtpd, Double factconv, Double costDev, Integer numAlm, Double mindirecto, Integer numMov, Double totPartida, String manIeps, Integer aplManImp, Double cuotaIeps, String aplManIeps, Double mtoPorc, Double mtoCuota, Integer cveEsq, String descrArt) {
       this.id = id;
       this.cveArt = cveArt;
       this.cant = cant;
       this.pxr = pxr;
       this.prec = prec;
       this.cost = cost;
       this.impu1 = impu1;
       this.impu2 = impu2;
       this.impu3 = impu3;
       this.impu4 = impu4;
       this.imp1apla = imp1apla;
       this.imp2apla = imp2apla;
       this.imp3apla = imp3apla;
       this.imp4apla = imp4apla;
       this.totimp1 = totimp1;
       this.totimp2 = totimp2;
       this.totimp3 = totimp3;
       this.totimp4 = totimp4;
       this.descu = descu;
       this.actInv = actInv;
       this.tipCam = tipCam;
       this.uniVenta = uniVenta;
       this.tipoElem = tipoElem;
       this.tipoProd = tipoProd;
       this.cveObs = cveObs;
       this.regSerie = regSerie;
       this.ELtpd = ELtpd;
       this.factconv = factconv;
       this.costDev = costDev;
       this.numAlm = numAlm;
       this.mindirecto = mindirecto;
       this.numMov = numMov;
       this.totPartida = totPartida;
       this.manIeps = manIeps;
       this.aplManImp = aplManImp;
       this.cuotaIeps = cuotaIeps;
       this.aplManIeps = aplManIeps;
       this.mtoPorc = mtoPorc;
       this.mtoCuota = mtoCuota;
       this.cveEsq = cveEsq;
       this.descrArt = descrArt;
    }
   
    public ParCompc01Id getId() {
        return this.id;
    }
    
    public void setId(ParCompc01Id id) {
        this.id = id;
    }
    public String getCveArt() {
        return this.cveArt;
    }
    
    public void setCveArt(String cveArt) {
        this.cveArt = cveArt;
    }
    public Double getCant() {
        return this.cant;
    }
    
    public void setCant(Double cant) {
        this.cant = cant;
    }
    public Double getPxr() {
        return this.pxr;
    }
    
    public void setPxr(Double pxr) {
        this.pxr = pxr;
    }
    public Double getPrec() {
        return this.prec;
    }
    
    public void setPrec(Double prec) {
        this.prec = prec;
    }
    public Double getCost() {
        return this.cost;
    }
    
    public void setCost(Double cost) {
        this.cost = cost;
    }
    public Double getImpu1() {
        return this.impu1;
    }
    
    public void setImpu1(Double impu1) {
        this.impu1 = impu1;
    }
    public Double getImpu2() {
        return this.impu2;
    }
    
    public void setImpu2(Double impu2) {
        this.impu2 = impu2;
    }
    public Double getImpu3() {
        return this.impu3;
    }
    
    public void setImpu3(Double impu3) {
        this.impu3 = impu3;
    }
    public Double getImpu4() {
        return this.impu4;
    }
    
    public void setImpu4(Double impu4) {
        this.impu4 = impu4;
    }
    public Short getImp1apla() {
        return this.imp1apla;
    }
    
    public void setImp1apla(Short imp1apla) {
        this.imp1apla = imp1apla;
    }
    public Short getImp2apla() {
        return this.imp2apla;
    }
    
    public void setImp2apla(Short imp2apla) {
        this.imp2apla = imp2apla;
    }
    public Short getImp3apla() {
        return this.imp3apla;
    }
    
    public void setImp3apla(Short imp3apla) {
        this.imp3apla = imp3apla;
    }
    public Short getImp4apla() {
        return this.imp4apla;
    }
    
    public void setImp4apla(Short imp4apla) {
        this.imp4apla = imp4apla;
    }
    public Double getTotimp1() {
        return this.totimp1;
    }
    
    public void setTotimp1(Double totimp1) {
        this.totimp1 = totimp1;
    }
    public Double getTotimp2() {
        return this.totimp2;
    }
    
    public void setTotimp2(Double totimp2) {
        this.totimp2 = totimp2;
    }
    public Double getTotimp3() {
        return this.totimp3;
    }
    
    public void setTotimp3(Double totimp3) {
        this.totimp3 = totimp3;
    }
    public Double getTotimp4() {
        return this.totimp4;
    }
    
    public void setTotimp4(Double totimp4) {
        this.totimp4 = totimp4;
    }
    public Double getDescu() {
        return this.descu;
    }
    
    public void setDescu(Double descu) {
        this.descu = descu;
    }
    public String getActInv() {
        return this.actInv;
    }
    
    public void setActInv(String actInv) {
        this.actInv = actInv;
    }
    public Double getTipCam() {
        return this.tipCam;
    }
    
    public void setTipCam(Double tipCam) {
        this.tipCam = tipCam;
    }
    public String getUniVenta() {
        return this.uniVenta;
    }
    
    public void setUniVenta(String uniVenta) {
        this.uniVenta = uniVenta;
    }
    public String getTipoElem() {
        return this.tipoElem;
    }
    
    public void setTipoElem(String tipoElem) {
        this.tipoElem = tipoElem;
    }
    public String getTipoProd() {
        return this.tipoProd;
    }
    
    public void setTipoProd(String tipoProd) {
        this.tipoProd = tipoProd;
    }
    public Integer getCveObs() {
        return this.cveObs;
    }
    
    public void setCveObs(Integer cveObs) {
        this.cveObs = cveObs;
    }
    public Integer getRegSerie() {
        return this.regSerie;
    }
    
    public void setRegSerie(Integer regSerie) {
        this.regSerie = regSerie;
    }
    public Integer getELtpd() {
        return this.ELtpd;
    }
    
    public void setELtpd(Integer ELtpd) {
        this.ELtpd = ELtpd;
    }
    public Double getFactconv() {
        return this.factconv;
    }
    
    public void setFactconv(Double factconv) {
        this.factconv = factconv;
    }
    public Double getCostDev() {
        return this.costDev;
    }
    
    public void setCostDev(Double costDev) {
        this.costDev = costDev;
    }
    public Integer getNumAlm() {
        return this.numAlm;
    }
    
    public void setNumAlm(Integer numAlm) {
        this.numAlm = numAlm;
    }
    public Double getMindirecto() {
        return this.mindirecto;
    }
    
    public void setMindirecto(Double mindirecto) {
        this.mindirecto = mindirecto;
    }
    public Integer getNumMov() {
        return this.numMov;
    }
    
    public void setNumMov(Integer numMov) {
        this.numMov = numMov;
    }
    public Double getTotPartida() {
        return this.totPartida;
    }
    
    public void setTotPartida(Double totPartida) {
        this.totPartida = totPartida;
    }
    public String getManIeps() {
        return this.manIeps;
    }
    
    public void setManIeps(String manIeps) {
        this.manIeps = manIeps;
    }
    public Integer getAplManImp() {
        return this.aplManImp;
    }
    
    public void setAplManImp(Integer aplManImp) {
        this.aplManImp = aplManImp;
    }
    public Double getCuotaIeps() {
        return this.cuotaIeps;
    }
    
    public void setCuotaIeps(Double cuotaIeps) {
        this.cuotaIeps = cuotaIeps;
    }
    public String getAplManIeps() {
        return this.aplManIeps;
    }
    
    public void setAplManIeps(String aplManIeps) {
        this.aplManIeps = aplManIeps;
    }
    public Double getMtoPorc() {
        return this.mtoPorc;
    }
    
    public void setMtoPorc(Double mtoPorc) {
        this.mtoPorc = mtoPorc;
    }
    public Double getMtoCuota() {
        return this.mtoCuota;
    }
    
    public void setMtoCuota(Double mtoCuota) {
        this.mtoCuota = mtoCuota;
    }
    public Integer getCveEsq() {
        return this.cveEsq;
    }
    
    public void setCveEsq(Integer cveEsq) {
        this.cveEsq = cveEsq;
    }
    public String getDescrArt() {
        return this.descrArt;
    }
    
    public void setDescrArt(String descrArt) {
        this.descrArt = descrArt;
    }




}


