package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * ParCompcClib01Id generated by hbm2java
 */
public class ParCompcClib01Id  implements java.io.Serializable {


     private String claveDoc;
     private int numPart;

    public ParCompcClib01Id() {
    }

    public ParCompcClib01Id(String claveDoc, int numPart) {
       this.claveDoc = claveDoc;
       this.numPart = numPart;
    }
   
    public String getClaveDoc() {
        return this.claveDoc;
    }
    
    public void setClaveDoc(String claveDoc) {
        this.claveDoc = claveDoc;
    }
    public int getNumPart() {
        return this.numPart;
    }
    
    public void setNumPart(int numPart) {
        this.numPart = numPart;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParCompcClib01Id) ) return false;
		 ParCompcClib01Id castOther = ( ParCompcClib01Id ) other; 
         
		 return ( (this.getClaveDoc()==castOther.getClaveDoc()) || ( this.getClaveDoc()!=null && castOther.getClaveDoc()!=null && this.getClaveDoc().equals(castOther.getClaveDoc()) ) )
 && (this.getNumPart()==castOther.getNumPart());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getClaveDoc() == null ? 0 : this.getClaveDoc().hashCode() );
         result = 37 * result + this.getNumPart();
         return result;
   }   


}


