package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * ParCompc01Id generated by hbm2java
 */
public class ParCompc01Id  implements java.io.Serializable {


     private String cveDoc;
     private int numPar;

    public ParCompc01Id() {
    }

    public ParCompc01Id(String cveDoc, int numPar) {
       this.cveDoc = cveDoc;
       this.numPar = numPar;
    }
   
    public String getCveDoc() {
        return this.cveDoc;
    }
    
    public void setCveDoc(String cveDoc) {
        this.cveDoc = cveDoc;
    }
    public int getNumPar() {
        return this.numPar;
    }
    
    public void setNumPar(int numPar) {
        this.numPar = numPar;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParCompc01Id) ) return false;
		 ParCompc01Id castOther = ( ParCompc01Id ) other; 
         
		 return ( (this.getCveDoc()==castOther.getCveDoc()) || ( this.getCveDoc()!=null && castOther.getCveDoc()!=null && this.getCveDoc().equals(castOther.getCveDoc()) ) )
 && (this.getNumPar()==castOther.getNumPar());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCveDoc() == null ? 0 : this.getCveDoc().hashCode() );
         result = 37 * result + this.getNumPar();
         return result;
   }   


}


