package com.etiquetas.qrsys.s.model;
// Generated Jul 18, 2018 1:30:24 PM by Hibernate Tools 4.3.1



/**
 * Tblcontrol01 generated by hbm2java
 */
public class Tblcontrol01  implements java.io.Serializable {


     private int idTabla;
     private Integer ultCve;

    public Tblcontrol01() {
    }

	
    public Tblcontrol01(int idTabla) {
        this.idTabla = idTabla;
    }
    public Tblcontrol01(int idTabla, Integer ultCve) {
       this.idTabla = idTabla;
       this.ultCve = ultCve;
    }
   
    public int getIdTabla() {
        return this.idTabla;
    }
    
    public void setIdTabla(int idTabla) {
        this.idTabla = idTabla;
    }
    public Integer getUltCve() {
        return this.ultCve;
    }
    
    public void setUltCve(Integer ultCve) {
        this.ultCve = ultCve;
    }




}


