package com.etiquetas.qrsys.e.model;
// Generated Aug 1, 2018 12:04:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idfactura;
     private String nofactura;
     private Date fecha;
     private int idusuario;
     private String proveedor;
     private String tipo;
     private String subtipo;
     private String esquema;
     private Double tipocambio;
     private String moneda;
     private String almacen;
     private String observacion;
     private String idproveedor;
     private Integer idalmacen;
     private Integer cveobs;
     private Set series = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idfactura, String nofactura, Date fecha, int idusuario) {
        this.idfactura = idfactura;
        this.nofactura = nofactura;
        this.fecha = fecha;
        this.idusuario = idusuario;
    }
    public Factura(int idfactura, String nofactura, Date fecha, int idusuario, String proveedor, String tipo, String subtipo, String esquema, Double tipocambio, String moneda, String almacen, String observacion, String idproveedor, Integer idalmacen, Integer cveobs, Set series) {
       this.idfactura = idfactura;
       this.nofactura = nofactura;
       this.fecha = fecha;
       this.idusuario = idusuario;
       this.proveedor = proveedor;
       this.tipo = tipo;
       this.subtipo = subtipo;
       this.esquema = esquema;
       this.tipocambio = tipocambio;
       this.moneda = moneda;
       this.almacen = almacen;
       this.observacion = observacion;
       this.idproveedor = idproveedor;
       this.idalmacen = idalmacen;
       this.cveobs = cveobs;
       this.series = series;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public String getNofactura() {
        return this.nofactura;
    }
    
    public void setNofactura(String nofactura) {
        this.nofactura = nofactura;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public String getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(String proveedor) {
        this.proveedor = proveedor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getSubtipo() {
        return this.subtipo;
    }
    
    public void setSubtipo(String subtipo) {
        this.subtipo = subtipo;
    }
    public String getEsquema() {
        return this.esquema;
    }
    
    public void setEsquema(String esquema) {
        this.esquema = esquema;
    }
    public Double getTipocambio() {
        return this.tipocambio;
    }
    
    public void setTipocambio(Double tipocambio) {
        this.tipocambio = tipocambio;
    }
    public String getMoneda() {
        return this.moneda;
    }
    
    public void setMoneda(String moneda) {
        this.moneda = moneda;
    }
    public String getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(String almacen) {
        this.almacen = almacen;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(String idproveedor) {
        this.idproveedor = idproveedor;
    }
    public Integer getIdalmacen() {
        return this.idalmacen;
    }
    
    public void setIdalmacen(Integer idalmacen) {
        this.idalmacen = idalmacen;
    }
    public Integer getCveobs() {
        return this.cveobs;
    }
    
    public void setCveobs(Integer cveobs) {
        this.cveobs = cveobs;
    }
    public Set getSeries() {
        return this.series;
    }
    
    public void setSeries(Set series) {
        this.series = series;
    }




}


