package com.etiquetas.qrsys.e.model;
// Generated Aug 1, 2018 12:04:30 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int idperfil;
     private String descripcion;
     private Set usuarios = new HashSet(0);

    public Perfil() {
    }

	
    public Perfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public Perfil(int idperfil, String descripcion, Set usuarios) {
       this.idperfil = idperfil;
       this.descripcion = descripcion;
       this.usuarios = usuarios;
    }
   
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


