package com.etiquetas.qrsys.e.model;
// Generated Aug 1, 2018 12:04:30 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idusuario;
     private Perfil perfil;
     private String nombre;
     private String password;
     private String correo;
     private Date fecha;
     private boolean estado;
     private String almacen;
     private Set series = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idusuario, Perfil perfil, String nombre, String password, String correo, Date fecha, boolean estado, String almacen) {
        this.idusuario = idusuario;
        this.perfil = perfil;
        this.nombre = nombre;
        this.password = password;
        this.correo = correo;
        this.fecha = fecha;
        this.estado = estado;
        this.almacen = almacen;
    }
    public Usuario(int idusuario, Perfil perfil, String nombre, String password, String correo, Date fecha, boolean estado, String almacen, Set series) {
       this.idusuario = idusuario;
       this.perfil = perfil;
       this.nombre = nombre;
       this.password = password;
       this.correo = correo;
       this.fecha = fecha;
       this.estado = estado;
       this.almacen = almacen;
       this.series = series;
    }
   
    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getAlmacen() {
        return this.almacen;
    }
    
    public void setAlmacen(String almacen) {
        this.almacen = almacen;
    }
    public Set getSeries() {
        return this.series;
    }
    
    public void setSeries(Set series) {
        this.series = series;
    }




}


